name: Deploy FastAPI to Railway

on:
  push:
    branches:
      - main   # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Railway
        uses: railwayapp/railway-action@v1
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
          service: fastapi-copilot   # Replace with your Railway service name
          environment: production    # Optional: set Railway environment
